title: Zwift
description: Easily Zwift on Linux
baseurl: "/zwift"
url: "https://netbrain.github.io"
repository: netbrain/zwift
permalink: pretty
back_to_top: true
back_to_top_text: "Back to top"
aux_links:
  "Zwift on GitHub":
    - "https://github.com/netbrain/zwift"
remote_theme: just-the-docs/just-the-docs@v0.12.0
plugins:
  - jemoji
