title: netbrain/zwift
description: Easily Zwift on Linux
repository: netbrain/zwift
permalink: pretty
back_to_top: true
back_to_top_text: "Back to top"
aux_links:
  "netbrain/zwift on GitHub":
    - "https://github.com/netbrain/zwift"
nav_external_links:
  - title: netbrain/zwift on GitHub
    url: https://github.com/netbrain/zwift
remote_theme: just-the-docs/just-the-docs@v0.12.0
plugins:
  - jemoji
