---
name: Validate bash scripts
on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - ".github/workflows/lint_bash_scripts.yaml"
      - "**.sh"
  push:
    paths:
      - ".github/workflows/lint_bash_scripts.yaml"
      - "**.sh"
jobs:
  validate-shell-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
      - name: Install bash language tools
        run: sudo apt-get install -y shellcheck
      - name: Check bash scripts for errors and warnings
        run: find . -path ./.git -prune -o -name "*.sh" -exec shellcheck {} +
  check-shell-scripts-formatted:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.23"
      - name: Install bash language tools
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
      - name: Check if bash scripts are formatted
        run: shfmt -d .
