name: Validate bash scripts
on:
  pull_request:
    paths:
      - '.github/workflows/lint_bash_scripts.yaml'
      - '**.sh'
  push:
    paths:
      - '.github/workflows/lint_bash_scripts.yaml'
      - '**.sh'
jobs:
  validate-shell-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
      - name: Install bash language tools
        run: sudo apt-get install -y shellcheck
      - name: Check bash scripts for errors and warnings
        run: find . -path ./.git -prune -o -name "*.sh" -exec shellcheck {} +
